### ISSUE TITLE
Linear Combination Print Issue

### ISSUE THREAD

**Issue by jazon7** [arhumkhan/euclidean-linear-combination#1]
The printing of linear combination equation, e.g. 1 = 11(53) - 6(97), was sometimes backwards. 

A simple if statement to switch the order based on the 'diff' value did the trick. 

For example. If the diff value was 1, print as normal. If diff value was -1 to switch the order of the equation.

**Comment by arhumkhan** [comment]
Nice catch, working on a fix! And thank you - somehow never got notified for this and it's nice to revisit this old project after all this time.

**Comment by jazon7** [comment]
Your welcome. But I had completely forgotten about this. :)

BTW. This program really helped me with my Cryptography course!

**Comment by arhumkhan** [comment]
Wow, cryptography! That's amazing! I'm really happy to hear that and it means a lot that it helped you out. Thank you!
